<a href="https://colab.research.google.com/github/ThanhNhu-20104049/Tri-tue-nhan-tao/blob/main/AI%2011-10-2022(ANN).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#ANN ARTIFICIAL NEURAL NETWORK
'''Perception - Binary network - classification (Phân loại)
Multi Layer perception (Mạng nhiều lớp)
CNN (Convilutional NN - Mạng tích chập)
RNN
Natural Language Processing)
Yolo'''


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
x = [[0,0],[1,0],[0,1],[1,1]] 
y = [0,1,1,1]
model = Perceptron()
#Dạy trên tập x,y
model.fit(x,y)
#Score xác định độ chính xác
print('Độ chính xác', model.score(x,y))
x_test = [[0.5,0],[0.9,0.2],[1,0.5],[0.2,0.7]]
y_test = model.predict(x_test)
print(y_test)

Độ chính xác 1.0
[0 1 1 1]


In [ ]:

x = [[-0.5,-0.5],[-0.5,0.5],[0.3,-0.5],[-0.1,1]] 
y = [1,1,0,0]
model = Perceptron()
#Dạy trên tập x,y
model.fit(x,y)
#Score xác định độ chính xác
print('Độ chính xác', model.score(x,y))
x_test = [[-0.5,0],[0.1,0.5],[1,0.5],[0.2,0.7]]
y_test = model.predict(x_test)
print(y_test)

Độ chính xác 1.0
[1 0 0 0]


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
#train_step_list: chia dữ liệu
from sklearn.model_selection import train_test_split 
import pandas as pd

url = 'crabs.csv'
data = pd.read_csv(url)
data = data[:100]
x= data.drop(['speies','sex','index'],axis = True)

y= data['sex'].replace(['M','F'],['1','0'])

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

model = Perceptron()
model.fit(x_train,y_train)
print('Độ chính xác', model.score(x_train,y_train))

x_t = [[8.1,6.7,16.1,19,7],[10.4,9.7,21.7,25.4,8.3]]
y_t = model.predict(x_t)

print(y_t)

Độ chính xác 0.9
['0' '0']


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import pandas as pd

url = "crabs.csv"
data = pd.read_csv(url)
x = data.drop(data.columns[[0,1,2]], axis=True)
y = data["sex"].replace(["M","F"],[1,0])

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

model = Perceptron()
model.fit(x_train, y_train)
print("Độ chính xác: ", model.score(x_train,y_train))

x_t = [[8.1,6.7,16.1,19,7],[10.4,9.7,21.7,25.4,8.3]]
y_t = model.predict(x_t)

print(y_t)

Độ chính xác:  0.7285714285714285
[0 0]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split 
from sklearn.datasets import load_iris
import pandas as pd
url = 'iris.csv'
data = pd.read_csv(url)
data = data[:100]

x= data.drop(['variety'],axis = True)
y= data['variety'].replace(['Setosa','Versicolor','Virginica'],[1,0,0])

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

model = Perceptron()
model.fit(x_train,y_train)
print('Độ chính xác', model.score(x_train,y_train))
x_in = [[3.6,4.4,1.4,0.3],[6.7,3,5.2,2.7],[6.3,2.3,4.4,1.3],[5.1,3.8,1.9,0.4]]
y_out = model.predict(x_in)
print(y_out)


Độ chính xác 1.0
[1 0 0 1]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"
